name: Exercise on AWS Secret and Variable Retrieval - CE3 Group4 Justin Cheemeng Siying Nicholas

on:
  push:
    branches:
      - main

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      - name: Get Secret Object
        run: |
          secret_object=$(aws secretsmanager get-secret-value --secret-id dev/superheroes --query SecretString --output json)

          # Parse specific keys from the secret object
          secret_value_superhero1=$(echo "$secret_object" | jq -r '. | fromjson | .superhero1')
          secret_value_superhero2=$(echo "$secret_object" | jq -r '. | fromjson | .superhero2')
          secret_value_superhero3=$(echo "$secret_object" | jq -r '. | fromjson | .superhero3')

          echo "Secret value Superhero1 is: $secret_value_superhero1"
          echo "Secret value Superhero2 is: $secret_value_superhero2"
          echo "Secret value Superhero3 is: $secret_value_superhero3"

  retrieve_parameters:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"

      # Firstly, insert your parameter in AWS Systems Manager > Parameter Store
      # Then, you can retrieve the parameters using aws ssm get-parameter command

      - name: Get parameter object
        run: |
          villians_value=$(aws ssm get-parameter --name villians --query Parameter.Value --output text)
          echo "The villians are: $villians_value" 